[proxmox_nodes]
HVA02 ansible_host=10.25.25.249 ansible_user=root

[controllers]
k8s-controller-01 ansible_host=10.25.25.5

[workers]
k8s-worker-01 ansible_host=10.25.25.6

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa_terraform