#!/usr/bin/env bash
# Disclaimer: This script was (mostly) generated by AI.
set -euo pipefail

VAULT_NAME="kv-homelab-prod-uks-3"

echo "=== Fetching configuration and credentials from Azure Key Vault ==="

backend_rg=$(az keyvault secret show --name "backend-resource-group" --vault-name "$VAULT_NAME" --query value -o tsv)
backend_storage=$(az keyvault secret show --name "backend-storage-account" --vault-name "$VAULT_NAME" --query value -o tsv)
backend_container=$(az keyvault secret show --name "backend-container-name" --vault-name "$VAULT_NAME" --query value -o tsv)
backend_key=$(az keyvault secret show --name "backend-state-key" --vault-name "$VAULT_NAME" --query value -o tsv)

pve_username=$(az keyvault secret show --name "pve-username" --vault-name "$VAULT_NAME" --query value -o tsv)
pve_password=$(az keyvault secret show --name "pve-password" --vault-name "$VAULT_NAME" --query value -o tsv)
tenant_id=$(az keyvault secret show --name "tenant-id" --vault-name "$VAULT_NAME" --query value -o tsv)

echo "✓ All secrets downloaded safely."
echo "=== Initializing Terraform with Dynamic Backend ==="

terraform init -reconfigure \
  -backend-config="resource_group_name=${backend_rg}" \
  -backend-config="storage_account_name=${backend_storage}" \
  -backend-config="container_name=${backend_container}" \
  -backend-config="key=${backend_key}" \
  -backend-config="use_azuread_auth=true"

echo "=== Running Terraform Plan ==="

terraform plan \
  -var-file="homelab.tfvars" \
  -out="tfplan" \
  -var="pve_username=${pve_username}" \
  -var="pve_password=${pve_password}" \
  -var="tenant_id=${tenant_id}"