---
- name: Secure Host SSH Configurations
  hosts: command_vms
  become: true
  gather_facts: false

  tasks:
    - name: Generate SSH key
      ansible.builtin.shell:
        cmd: ssh-keygen -t rsa -b 4096 -m PEM -f ~/.ssh/id_rsa_terraform -N ""
        creates: ~/.ssh/id_rsa_terraform
      become: false

    - name: Read public key
      ansible.builtin.slurp:
        src: "~/.ssh/id_rsa_terraform.pub"
      become: false
      register: terraform_pub_key

    - name: Copy key to proxmox node
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ terraform_pub_key['content'] | b64decode }}"

    - name: Harden SSH config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
        - { regexp: '^#?KbdInteractiveAuthentication', line: 'KbdInteractiveAuthentication no' }
      notify: Restart SSH Daemon

  handlers:
    - name: Restart SSH Daemon
      ansible.builtin.service:
        name: ssh
        state: restarted

- name: Configure Commander VM
  hosts: command_vms
  become: true
  gather_facts: true

  vars:
    galaxy_collections:
      - kubernetes.core
      - azure.azcollection
      - ansible.posix
      - community.general

  tasks:
    - name: Ensure system is fully updated
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install baseline dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
          - python3-pip
        state: present

    - name: HashiCorp GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Microsoft GPG key
      ansible.builtin.shell:
        cmd: >-
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
        creates: /etc/apt/keyrings/microsoft.gpg

    - name: PowerShell GPG Key
      ansible.builtin.shell:
        cmd: >-
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
        creates: /etc/apt/keyrings/microsoft.gpg

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
        state: present
        filename: hashicorp

    - name: Add Azure CLI repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_facts['distribution_release'] }} main"
        state: present
        filename: azure-cli

    - name: Add Microsoft PowerShell repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ ansible_facts['distribution_release'] }}-prod {{ ansible_facts['distribution_release'] }} main"
        state: present
        filename: powershell


    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: true

    - name: Install Azure CLI
      ansible.builtin.apt:
        name: azure-cli
        state: present
        update_cache: true

    - name: Install Ansible
      ansible.builtin.apt:
        name: ansible
        state: present
        update_cache: true

    - name: Install PowerShell
      ansible.builtin.apt:
        name: powershell
        state: present
        update_cache: true

    - name: Install Ansible Galaxy collections
      become: false
      ansible.builtin.command:
        cmd: "ansible-galaxy collection install {{ item }} --upgrade"
      loop: "{{ galaxy_collections }}"
      changed_when: true

    - name: Clone homelab-infra repo
      become: false
      ansible.builtin.git:
        repo: "https://github.com/mitchellmooreuk/homelab-infra.git"
        dest: "~/homelab-infra"
        version: main




