---
- name: Secure Host SSH Configurations
  hosts: proxmox_nodes
  become: true
  tasks:
  - name: Generate ssh key
    ansible.builtin.command:
      cmd: ssh-keygen -t rsa -b 4096 -m PEM -f "~/.ssh/id_rsa_terraform" -N ""
    delegate_to: localhost
    become: false
    args:
      creates: "~/.ssh/id_rsa_terraform"

  - name: Insert key into memory
    ansible.builtin.slurp:
      src: "~/.ssh/id_rsa_terraform.pub"
    delegate_to: localhost
    become: false
    register: terraform_pub_key

- name: Copy key to proxmox node
  hosts: proxmox_nodes
  gather_facts: false
  tasks:
    - name: Copy key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ terraform_pub_key['content'] | b64decode }}"

    - name: Harden SSH config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
        - { regexp: '^#?KbdInteractiveAuthentication', line: 'KbdInteractiveAuthentication no' }
      notify: Restart SSH Daemon

  handlers:
    - name: Restart SSH Daemon
      ansible.builtin.service:
        name: ssh
        state: restarted  