apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: docker.io/library/homelab-runner:v1
        imagePullPolicy: IfNotPresent 
        env:
        - name: GH_PAT
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: pat-token
        - name: GH_OWNER
          value: "mitchellmooreuk"
        - name: GH_REPO
          value: "homelab-infra"