---
- name: Secure Host SSH Configurations
  hosts: proxmox_nodes
  become: true
  vars:
    # Replace this with your actual public key string
    my_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC6P64Ta4IwU/C/5Zx2hkrNkKVRNYmHPnItNaIGmoAa5 mitchell@tcpit.co.uk" 

  tasks:
    - name: Ensure the .ssh directory exists for Root
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Add public key to /root/.ssh/authorized_keys
      ansible.builtin.authorized_key:
        user: root
        state: present
        key: "{{ my_public_key }}"

    - name: Harden SSH config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
        - { regexp: '^#?KbdInteractiveAuthentication', line: 'KbdInteractiveAuthentication no' }
      notify: Restart SSH Daemon

  handlers:
    - name: Restart SSH Daemon
      ansible.builtin.service:
        name: ssh
        state: restarted  