#!/usr/bin/env bash
# Disclaimer: This script was (mostly) generated by AI.
set -euo pipefail

key_vault_name="$1"
resource_group_name="$2"
storage_account_name="$3"

current_ip=$(curl -s https://ifconfig.me)

az storage account network-rule add \
  --resource-group "${resource_group_name}" \
  --account-name "${storage_account_name}" \
  --ip-address "$current_ip"

az keyvault network-rule add \
  --name "${key_vault_name}" \
  --ip-address "$current_ip"

echo "=== Fetching configuration and credentials from Azure Key Vault ==="
backend_container=$(az keyvault secret show --name "backend-container-name" --vault-name "$key_vault_name" --query value -o tsv)
backend_key_HVA01=$(az keyvault secret show --name "backend-state-key-HVA01" --vault-name "$key_vault_name" --query value -o tsv)
HVA01_api_token=$(az keyvault secret show --name "HVA01-api-token" --vault-name "$key_vault_name" --query value -o tsv)
tenant_id=$(az keyvault secret show --name "tenant-id" --vault-name "$key_vault_name" --query value -o tsv)

echo "✓ All secrets downloaded safely."
echo "=== Initializing Terraform with Dynamic Backend ==="
terraform init -reconfigure \
  -backend-config="resource_group_name=${resource_group_name}" \
  -backend-config="storage_account_name=${storage_account_name}" \
  -backend-config="container_name=${backend_container}" \
  -backend-config="key=${backend_key_HVA01}" \
  -backend-config="use_azuread_auth=true"

echo "=== Running Terraform Plan ==="
terraform plan \
  -var-file="core.tfvars" \
  -out="tfplan" \
  -var="pve_api_token=${HVA01_api_token}" \
  -var="tenant_id=${tenant_id}" 