name: Deploy - Terraform - All

on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Application to deploy'
        required: true
        type: choice
        options:
          - HVA01
          - HVA02
          - Azure
      deploy-prod:
        description: 'Prod'
        type: boolean
        default: false

jobs:
  deploy-prod:
    if: inputs.deploy-prod == true
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy_template.yml
    with:
      application: ${{ inputs.application }}
      environment: Prod
      resource_group_name: ${{ vars.RESOURCE_GROUP_NAME }}
      storage_account_name: ${{ vars.STORAGE_ACCOUNT_NAME }}
      container_name: ${{ vars.CONTAINER_NAME }}
      working-directory: ${{ (inputs.application == 'HVA01' || inputs.application == 'HVA02') && 'Hypervisors/terraform' || 'Azure' }}
    secrets:
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      pve_api_token: ${{ secrets[format('{0}_PVE_API_TOKEN', inputs.application)] }}